/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.movieTheater.gui.popUpDialog;

import hr.algebra.utils.MessageUtils;
import hr.movieTheater.dal.Repository;
import hr.movieTheater.dal.RepositorySingleton;
import hr.movieTheater.log.LogHandler;
import hr.movieTheater.log.LogHandlerSingleton;
import hr.movieTheater.model.Genre;
import hr.movieTheater.model.GenreTransferable;
import java.awt.Dialog;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.DropMode;
import javax.swing.JComponent;
import javax.swing.ListSelectionModel;
import javax.swing.TransferHandler;

/**
 *
 * @author Josip
 */
public class DragAndDropGenrePanel extends javax.swing.JPanel {

    private Repository repo;
    private LogHandler logHandler;
    
    private DragAndDropDialog parent;
    private Set<Genre> genres;
    private Set<Genre> allGenres;
    
    private Set<Genre> searchResult;
    private String typedString = "";
    
    private DefaultListModel<Genre> genresModel;
    private DefaultListModel<Genre> allGenresModel;
    
    /**
     * Creates new form DragAndDropGenrePanel
     */
//    public DragAndDropGenrePanel() {
//        initComponents();
//    }

    DragAndDropGenrePanel(DragAndDropDialog parent, List<Genre> genres) {
        this.parent = parent;
        this.genres = new TreeSet<>(genres);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsGenres = new javax.swing.JList<Genre>();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsAllGenres = new javax.swing.JList<Genre>();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lsGenres);

        btnRemove.setText("Obriši");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lsAllGenres);

        btnCancel.setText("Odustani");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Spremi");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAdd.setText("Dodaj novi žanr");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(tfSearch)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        genres.remove(lsGenres.getSelectedValue());
        loadGenresModel(genres);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        parent.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        parent.setGenres(new ArrayList<>(genres));
        parent.saveData();
        parent.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new AddNewGenre((Dialog) this.getParent().getParent().getParent().getParent().getParent(), true).setVisible(true);
        initData();
        loadAllGenresModel(allGenres);
    }//GEN-LAST:event_btnAddActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        typedString = tfSearch.getText().trim();
        searchResult.clear();
        
        System.out.println(tfSearch.getText().trim());
        System.out.println(typedString);
        
        if (0 != typedString.length()) {
            for (Genre genre : allGenres) {
                if (genre.getName().toLowerCase().startsWith(typedString.toLowerCase())) {
                    searchResult.add(genre);
                }
            }
            loadAllGenresModel(searchResult);
        }
        else{
            loadAllGenresModel(allGenres);
        }
    }//GEN-LAST:event_tfSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Genre> lsAllGenres;
    private javax.swing.JList<Genre> lsGenres;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

    private void init() {
        initLogHandler();
        initRepositiry();
        initData();
        initModels();
        initDragAndDrop();
        searchResult = new TreeSet<>();
    }

    private void initLogHandler() {
        logHandler = LogHandlerSingleton.getInstance();
    }

    private void initRepositiry() {
        repo = RepositorySingleton.getInstance();
    }

    private void initData() {
        try {
            allGenres = new TreeSet<>(repo.getGenres());
        } catch (SQLException ex) {
            logHandler.log(ex.getMessage(), ex);
            MessageUtils.showErrorMessage("Error br. 10", "Došlo je do pogreške tijekom dohvačanja podatka. Za pomoć obratite se adminu.");
            Logger.getLogger(DragAndDropGenrePanel.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception ex) {
            logHandler.log(ex.getMessage(), ex);
            MessageUtils.showErrorMessage("Error br. 100", "Došlo je do nepoznate pogreške. Javite se adminu.");
        }
    }

    private void initModels() {
        genresModel = new DefaultListModel<>();
        allGenresModel = new DefaultListModel<>();
        loadGenresModel(genres);
        loadAllGenresModel(allGenres);
    }

    private void loadGenresModel(Set<Genre> z) {
        genresModel.clear();
        z.forEach(g -> genresModel.addElement(g));
        lsGenres.setModel(genresModel);
    }

    private void loadAllGenresModel(Set<Genre> z) {
        allGenresModel.clear();
        System.out.println("proslo");
        z.forEach(g -> allGenresModel.addElement(g));
        lsAllGenres.setModel(allGenresModel);
    }

    private void initDragAndDrop() {
        lsAllGenres.setDragEnabled(true);
        lsAllGenres.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsAllGenres.setTransferHandler(new ExsportHandler());
        
        lsGenres.setDropMode(DropMode.ON);
        lsGenres.setTransferHandler(new ImoportHandler());
    }
    
    
    private class ExsportHandler extends TransferHandler{

        @Override
        public int getSourceActions(JComponent c) {
            return COPY;
        }
        
        @Override
        protected Transferable createTransferable(JComponent c) {
            return new GenreTransferable(lsAllGenres.getSelectedValue());
        }
        
    }
    
    private class ImoportHandler extends TransferHandler{

        @Override
        public boolean canImport(TransferSupport support) {
            return support.getDataFlavors().equals(GenreTransferable.SUPPORTED_FLAVORS);
        }

        @Override
        public boolean importData(TransferSupport support) {
            boolean ok = false;
            if (support.isDataFlavorSupported(GenreTransferable.GENRE_FLAVOR)) {
                Transferable data = support.getTransferable();
                try {
                    genres.add( (Genre) data.getTransferData(GenreTransferable.GENRE_FLAVOR));
                    loadGenresModel(genres);
                } catch (UnsupportedFlavorException | IOException ex) {
                    logHandler.log(ex.getMessage(), ex);
                    MessageUtils.showErrorMessage("Error br. 30", "Došlo je do pogreške tijekom dropanja. Za pomoc obratite se adminu.");
                    Logger.getLogger(DragAndDropGenrePanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                ok = true;
            }
            return ok;
        }
        
    }
}
